package kishouchou

object AreaCode {
  case class Office(
      code: String,
      name: String,
      enName: String,
      officeName: String
  )
  val Gunma     = Office("100000", "群馬県", "Gunma", "前橋地方気象台")
  val Saitama   = Office("110000", "埼玉県", "Saitama", "熊谷地方気象台")
  val Chiba     = Office("120000", "千葉県", "Chiba", "銚子地方気象台")
  val Tokyo     = Office("130000", "東京都", "Tokyo", "気象庁")
  val Kanagawa  = Office("140000", "神奈川県", "Kanagawa", "横浜地方気象台")
  val Niigata   = Office("150000", "新潟県", "Niigata", "新潟地方気象台")
  val Toyama    = Office("160000", "富山県", "Toyama", "富山地方気象台")
  val Ishikawa  = Office("170000", "石川県", "Ishikawa", "金沢地方気象台")
  val Fukui     = Office("180000", "福井県", "Fukui", "福井地方気象台")
  val Yamanashi = Office("190000", "山梨県", "Yamanashi", "甲府地方気象台")
  val Nagano    = Office("200000", "長野県", "Nagano", "長野地方気象台")
  val Gifu      = Office("210000", "岐阜県", "Gifu", "岐阜地方気象台")
  val Shizuoka  = Office("220000", "静岡県", "Shizuoka", "静岡地方気象台")
  val Aichi     = Office("230000", "愛知県", "Aichi", "名古屋地方気象台")
  val Mie       = Office("240000", "三重県", "Mie", "津地方気象台")
  val Shiga     = Office("250000", "滋賀県", "Shiga", "彦根地方気象台")
  val Kyoto     = Office("260000", "京都府", "Kyoto", "京都地方気象台")
  val Osaka     = Office("270000", "大阪府", "Osaka", "大阪管区気象台")
  val Hyogo     = Office("280000", "兵庫県", "Hyogo", "神戸地方気象台")
  val Nara      = Office("290000", "奈良県", "Nara", "奈良地方気象台")
  val Wakayama  = Office("300000", "和歌山県", "Wakayama", "和歌山地方気象台")
  val Tottori   = Office("310000", "鳥取県", "Tottori", "鳥取地方気象台")
  val Shimane   = Office("320000", "島根県", "Shimane", "松江地方気象台")
  val Okayama   = Office("330000", "岡山県", "Okayama", "岡山地方気象台")
  val Hiroshima = Office("340000", "広島県", "Hiroshima", "広島地方気象台")
  val Yamaguchi = Office("350000", "山口県", "Yamaguchi", "下関地方気象台")
  val Tokushima = Office("360000", "徳島県", "Tokushima", "徳島地方気象台")
  val Kagawa    = Office("370000", "香川県", "Kagawa", "高松地方気象台")
  val Ehime     = Office("380000", "愛媛県", "Ehime", "松山地方気象台")
  val Kochi     = Office("390000", "高知県", "Kochi", "高知地方気象台")
  val Fukuoka   = Office("400000", "福岡県", "Fukuoka", "福岡管区気象台")
  val Saga      = Office("410000", "佐賀県", "Saga", "佐賀地方気象台")
  val Nagasaki  = Office("420000", "長崎県", "Nagasaki", "長崎地方気象台")
  val Kumamoto  = Office("430000", "熊本県", "Kumamoto", "熊本地方気象台")
  val Oita      = Office("440000", "大分県", "Oita", "大分地方気象台")
  val Miyazaki  = Office("450000", "宮崎県", "Miyazaki", "宮崎地方気象台")
  val Amami     = Office("460040", "奄美地方", "Amami", "名瀬測候所")
  val Kagoshima_ExcludingAmami_ =
    Office("460100", "鹿児島県（奄美地方除く）", "Kagoshima (Excluding Amami)", "鹿児島地方気象台")
  val OkinawaMainIsland =
    Office("471000", "沖縄本島地方", "Okinawa Main Island", "沖縄気象台")
  val Daitojima     = Office("472000", "大東島地方", "Daitojima", "南大東島地方気象台")
  val Miyakojima    = Office("473000", "宮古島地方", "Miyakojima", "宮古島地方気象台")
  val Yaeyama       = Office("474000", "八重山地方", "Yaeyama", "石垣島地方気象台")
  val Soya          = Office("11000", "宗谷地方", "Soya", "稚内地方気象台")
  val KamikawaRumoi = Office("12000", "上川・留萌地方", "Kamikawa Rumoi", "旭川地方気象台")
  val AbashiriKitamiMombetsu =
    Office("13000", "網走・北見・紋別地方", "Abashiri Kitami Mombetsu", "網走地方気象台")
  val Tokachi       = Office("14030", "十勝地方", "Tokachi", "帯広測候所")
  val KushiroNemuro = Office("14100", "釧路・根室地方", "Kushiro Nemuro", "釧路地方気象台")
  val IburiHidaka   = Office("15000", "胆振・日高地方", "Iburi Hidaka", "室蘭地方気象台")
  val IshikariSorachiShiribeshi =
    Office("16000", "石狩・空知・後志地方", "Ishikari Sorachi Shiribeshi", "札幌管区気象台")
  val OshimaHiyama = Office("17000", "渡島・檜山地方", "Oshima Hiyama", "函館地方気象台")
  val Aomori       = Office("20000", "青森県", "Aomori", "青森地方気象台")
  val Iwate        = Office("30000", "岩手県", "Iwate", "盛岡地方気象台")
  val Miyagi       = Office("40000", "宮城県", "Miyagi", "仙台管区気象台")
  val Akita        = Office("50000", "秋田県", "Akita", "秋田地方気象台")
  val Yamagata     = Office("60000", "山形県", "Yamagata", "山形地方気象台")
  val Fukushima    = Office("70000", "福島県", "Fukushima", "福島地方気象台")
  val Ibaraki      = Office("80000", "茨城県", "Ibaraki", "水戸地方気象台")
  val Tochigi      = Office("90000", "栃木県", "Tochigi", "宇都宮地方気象台")
}
